# Generated by Django 4.1.7 on 2023-03-09 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_alter_usermodel_email_alter_usermodel_password_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usermodel',
            table='user',
        ),
    ]
